2013/02/01 22:03:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'hmnelson'@'localhost' (using password: YES)' in /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/db/CDbConnection.php:381
Stack trace:
#0 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModule.php(387): CDbConnection->init()
#3 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/auth/CDbAuthManager.php(589): CModule->getComponent('db')
#4 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/auth/CDbAuthManager.php(59): CDbAuthManager->getDbConnection()
#5 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModule.php(387): CDbAuthManager->init()
#6 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModule.php(103): CModule->getComponent('authManager')
#7 /Users/hmnelson/Sites/testyii/protected/modules/rights/RightsModule.php(129): CModule->__get('authManager')
#8 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModule.php(90): RightsModule->init()
#9 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/YiiBase.php(206): CModule->__construct('rights', NULL, Array)
#10 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModule.php(282): YiiBase::createComponent('rights.RightsMo...', 'rights', NULL, Array)
#11 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CWebApplication.php(337): CModule->getModule('rights')
#12 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CWebApplication.php(276): CWebApplication->createController('rights')
#13 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CWebApplication.php(141): CWebApplication->runController('rights')
#14 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Users/hmnelson/Sites/testyii/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testyii/index.php/site/index?r=rights
---
2013/02/01 22:06:38 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test-yii.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in /Users/hmnelson/Sites/testyii/protected/modules/user/models/User.php (33)
in /Users/hmnelson/Sites/testyii/protected/modules/user/components/UserIdentity.php (27)
in /Users/hmnelson/Sites/testyii/protected/models/LoginForm.php (52)
2013/02/01 22:06:38 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/db/ar/CActiveRecord.php:2310
Stack trace:
#0 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/db/ar/CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(User))
#1 /Users/hmnelson/Sites/testyii/protected/modules/user/models/User.php(33): CActiveRecord::model('User')
#2 /Users/hmnelson/Sites/testyii/protected/modules/user/components/UserIdentity.php(27): User::model()
#3 /Users/hmnelson/Sites/testyii/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /Users/hmnelson/Sites/testyii/protected/controllers/SiteController.php(94): CModel->validate()
#8 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CWebApplication.php(282): CController->run('login')
#13 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /Users/hmnelson/Sites/yii-1.1.13.e9e4a0/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Users/hmnelson/Sites/testyii/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testyii/index.php/site/login
HTTP_REFERER=http://localhost/testyii/index.php/site/login
---
2013/02/01 22:08:17 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'test-yii.AuthItem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in /Users/hmnelson/Sites/testyii/protected/modules/rights/components/RInstaller.php (180)
in /Users/hmnelson/Sites/testyii/protected/modules/rights/controllers/InstallController.php (43)
in /Users/hmnelson/Sites/testyii/index.php (13)
